### ISSUE TITLE
Finer grain for permissions

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#468] opened 2016-02-26 15:54 UTC
As per discussion with @chrismbeckett on IRC:

In business application, having write permissions doesn't means nor that you can delete the data nor that you can change its permissions.

We should probably let people define another sharable model for their Kinto Instance.

Today we have:

 - ProtectedResource
 - SharableResource

We may want to let people define other ones more complex with their own inheritance tree and another set of permissions or at least let them define which verb are link to which permission.

Keep in mind that without a collection schema it is possible to remove a records by putting an empty record instead, with the collection schema it is not possible to remove something by putting an empty record for instance but it is still possible to override it with wrong data.

Maybe we should investigate this use case and see what are the options to handle that.

**Comment by Natim** [comment] 2016-02-26 15:56
For the question of deletion, something that we had in mind is to mark the record as deleted and put it in a garbage collections (using a listener) and then having a job that remove very old items from the garbage.

**Comment by leplatrem** [comment] 2016-05-27 08:06
I marked this as a duplicate of #101

**Closed** 2016-05-27 08:06 UTC
Labels: duplicate, protocol, protocol:v2, question, scope: permissions
