### ISSUE TITLE
Support fields storage on collection endpoints

### ISSUE THREAD

**Issue by ametaireau** [Kinto/kinto#161] opened 2015-08-20 17:18 UTC
Currently, it's not possible to store metadata in the collection endpoints. Storing data outside of a record, and attached to a collection is proved to be useful in a number of cases.

When considering this proposal, @QuentinRoy was suggesting that we use "metadata" as a field name for `last_modified` and other internal properties, and store the collection data in "data".

**Comment by leplatrem** [comment] 2015-08-21 08:24
Looks like a duplicate of #158 :)

**Closed** 2015-08-21 09:13 UTC
Labels: duplicate, enhancement
