### ISSUE TITLE
Errors for default values in kinto-admin on a fresh setup

### ISSUE THREAD

**Issue by webwurst** [Kinto/kinto#1639] opened 2018-05-20 17:34 UTC
When I log into the kinto-admin and create a bucket and then a collection, I get these errors:
>    description: should be string
>    description: should be string
>    description: should be string

This happens on a fresh local setup, but also on https://kinto.dev.mozaws.net/v1/admin/#/buckets/test/collections/create

Maybe I should read some more of the tutorials first ,)
But I would expect the default values to be fine and maybe the error message could also be improved a bit.

**Comment by glasserc** [comment] 2018-05-22 17:10
Duplicate of #535.

**Closed by glasserc** 2018-05-22 17:10 UTC
