### ISSUE TITLE
On update, also update the parent last_modified value.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#285] opened 2015-11-20 10:08 UTC
Updating a record, should update the collection ``last_modified``
Updating a collection or a group should update the bucket ``last_modified``

Note: This can have an impact on how we handle schema versioning.

This would let us monitor bucket collection changes.

**Comment by tarekziade** [comment] 2015-11-20 13:22
dupe of https://github.com/Kinto/kinto/issues/286 - closing this one since the other one has more info+discussions

**Closed by tarekziade** 2015-11-20 13:22 UTC
Labels: enhancement, question
