### ISSUE TITLE
Retrieving last_modified information for "hidden" buckets

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto#1060] opened 2017-02-03 15:24 UTC
The `/permissions` endpoint allows inferring parent containers for resources the authenticated user has access to, which is great.

For example, when I get this entry:

```json
{
  "bucket_id": "blocklists-preview",
  "resource_name": "collection",
  "collection_id": "addons",
  "permissions": [
    "read",
    "read:attributes"
  ],
  "uri": "/buckets/blocklists-preview/collections/addons",
  "id": "addons"
}
```

I know I have read access to the `addons` collection in the `blocklists-preview` bucket, while the `blocklists-preview` itself is not listed if I query the `/buckets` endpoint. That's the only way I'm aware of to know about this information.

But we can't know about the `last_modified` of that bucket; no way to query the `/buckets/blocklists-preview` endpoint of I'm not allowed to, neither it can be listed under `/buckets` for the same reason.

Do you know any other way to access this information?

Context: having orderable entries in the kinto-admin sidebar (https://github.com/Kinto/kinto-admin/issues/118).

**Comment by Natim** [comment] 2017-02-03 23:46
I guess you cannot have this information if you don't have permission to have it so you should probably order them by bucket name/ bucket ID :)

**Comment by leplatrem** [comment] 2017-03-06 16:44
Yup, by design this information is not available. I'm closing, feel free to reopen with protest signs if necessary :D

**Closed by leplatrem** 2017-03-06 16:44 UTC
Labels: question
