### ISSUE TITLE
Prompt which cache backend type to use in kinto init

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1334] opened 2017-09-27 09:25 UTC
Following the addition of Memcached as a cache backend.

**Comment by furquan1993** [comment] 2017-10-04 15:00
I am new to python, and would like to get my hands dirty. This issue seems to be tagged easy-pick and i would like to contribute. Just guide me to the right direction, how to build the project and all and i will get started.

**Comment by Natim** [comment] 2017-10-04 15:09
The goal is to add a new step to the kinto init command to ask about the cache backend.

By default it would use the same as the storage backend but it could also ask to specify other backends (redis, memcached, postgresql, memory)

We should probably also add an option to the command to specify the cache backend with `--cache-backend memcached` for instance.

**Comment by leplatrem** [comment] 2017-10-05 08:20
Hi @furquan1993 :)
Welcome here!

First, you should have a local environment working (ie. tests should be all green). You can follow these steps:
https://kinto.readthedocs.io/en/stable/community.html#hack

Then, before starting to code, you need to make sure the goal of the issue is clear to you. As Natim said, the objective here is to prompt the user when running `kinto init`. We already do for the the storage backend, but we now want to do it for the cache, since we added the support of Memcached recently. 

Don't hesitate to ask any question! «Any» means: even those you believe to be stupid :)

Enjoy!

**Comment by mayurvadhavana** [comment] 2017-11-23 23:54
Hi @leplatrem !
As per your suggestion, I would like to express my interest in this project. Could you please give some information regarding project details?
Thanks in advance.

**Comment by leplatrem** [comment] 2017-11-24 09:35
> some information regarding project details?

What do you mean? 

First, do you grasp the scope of this new feature?

@furquan1993 you didn't ask question nor commented back. How are you doing?

**Comment by mayurvadhavana** [comment] 2017-11-25 11:28
Hi @leplatrem ,
Thanks for your message. 
I tried to understand this new scope. Goal here is to add other backend (redis,postgresql, memory) rather than default (storage backend).

**Comment by leplatrem** [comment] 2017-11-27 09:12
> Goal here is to add other backend (redis,postgresql, memory) rather than default (storage backend).

Well, the `memcache` backend is already implemented in the project. But it is not shown among the available choices for the *cache backend* when running `kinto init`. The storage backend is something else.

I suggest that you spend some time running Kinto locally and play with it, you'll probably find it easier later to implement this ;)

**Comment by mayurvadhavana** [comment] 2017-11-27 09:31
Hello @leplatrem 
Thanks. I will do that part. Which platform do you prefer for Kinto (Linux or Windows)?

**Comment by leplatrem** [comment] 2017-11-27 09:45
Kinto should theorically work fine on both.

But we won't be able to assist you much on Windows to get your setup working (python, postgresql, memcache etc.). So I would slightly recommend Linux :)

**Comment by mayurvadhavana** [comment] 2017-11-27 09:59
Thanks for prompt reply. I will go for Linux than.

**Comment by mayurvadhavana** [comment] 2017-12-01 20:58
Hi @leplatrem,
I found an error while installing kinto (followed Quick start steps from website)
Exception:
Traceback (most recent call last):
  File "/home/mayur/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/mayur/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/mayur/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/mayur/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/mayur/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/mayur/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/mayur/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/mayur/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/urllib3-1.22.dist-info

**Comment by leplatrem** [comment] 2017-12-03 00:57
It's not clear at all in the docs, but you should create and activate the virtualenv if you want to run it locally without root privileges...

Otherwise, since you are about to modify the code, you'll find easier to follow the *from sources* instructions :)

**Comment by mayurvadhavana** [comment] 2017-12-03 07:13
Hello @leplatrem ,
Thank you.

**Comment by skepticleo** [comment] 2018-02-19 16:30
Hey @leplatrem I would like to take this one, will send a pull request soon.

**Comment by leplatrem** [comment] 2018-04-20 08:07
@skepticleo do you need help? should someone else take over?

**Comment by skepticleo** [comment] 2018-04-20 08:33
@leplatrem sorry, It's been a bit hectic for me lately. If anyone else is interested in taking this up, they should go ahead.

**Comment by aimanparvaiz** [comment] 2018-05-21 23:13
@leplatrem should I give this a shot? I am done with https://github.com/Kinto/kinto/pull/1499 and can find some time to work on this.

**Comment by leplatrem** [comment] 2018-05-22 09:27
@aimanparvaiz yep! go ahead :)

**Comment by aimanparvaiz** [comment] 2018-05-26 16:14
https://github.com/Kinto/kinto/pull/1653

**Comment by aimanparvaiz** [comment] 2018-05-26 18:57
@leplatrem I have submitted PR, quick question though, some of these options (available in PR) are not valid in this case. So I have left them blank. Please let me know if I am missing something.
  Add documentation.
  Add tests. (done)
  Add a changelog entry.
  Add your name in the contributors file. (done)
  If you changed the HTTP API, update the API_VERSION constant and add an API changelog entry in the docs
  If you added a new configuration setting, update the kinto.tpl file with it.

**Comment by alexryabkov** [comment] 2018-09-04 21:04
I suppose the issue was fixed by PR #1653, could you please close it?

**Closed** 2018-09-04 21:08 UTC
Labels: easy-pick, help wanted
