### ISSUE TITLE
Swagger spec on most recent release doesn't validate

### ISSUE THREAD

**Issue by chartjes** [Kinto/kinto#1106] opened 2017-02-23 17:23 UTC
When evaluating the Swagger response available at https://firefox.settings.services.mozilla.com/v1/__api__, it does not validate correctly using the online validation tools available at https://swagger.io.

**Comment by gabisurita** [comment] 2017-02-23 17:38
The current master has already been fixed by https://github.com/Kinto/kinto/pull/1078, but it's still unreleased yet. The problem is related with using Json pointers on the response headers. Which pass the editor validator but at swagger.io.

**Comment by gabisurita** [comment] 2017-02-23 20:44
Closed by #1108

**Closed by gabisurita** 2017-02-23 20:44 UTC
Labels: bug, documentation
