### ISSUE TITLE
record:create permissions needs to access the schema.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#803] opened 2016-09-01 16:08 UTC
I had a quick chat with @enguerran who is planning to use Kinto with a similar use case than the formbuilder:

 - People can create collection with an associate schema in a bucket:
     - bucket_permissions: collection_create: Authenticated
     - collection_permissions: record:create: Authenticated

The problem if you do that is that people that needs to create record in the collection cannot actually access the schema.

However if you add the read permission on the collection, they can read the schema as well as all records in the collection (their and other's people onces.)

The use case there is to have the admin to be able to read all records and users to be able to see only their own records for a given collection.

We also want to be able to list the collection the user can administrate. It makes it impossible if we give the read permission on the collection.

A quick fix would be to allow to read the schema or the collection data if we give the `record:create` permission.

**Comment by leplatrem** [comment] 2016-09-06 07:36
> A quick fix would be to allow to read the schema

Could you elaborate ?

**Comment by Natim** [comment] 2016-09-06 09:45
Add `record:create` in the inheritence tree to imply `collection:read`

**Comment by leplatrem** [comment] 2016-09-13 12:56
Ok I think I get it. When a user has `record:create` we allow to read the collection metadata but not the list of records. I like it!

Note that for consistency we shall probably apply the same strategy for bucket metadata and `collection:create` and `group:create`

**Comment by ptgamr** [comment] 2016-09-17 06:34
@leplatrem  @Natim

If user has `record:create` permission, should he be able to list all the records that he created under that collection ?

Otherwise, he can't list his records. If we give him the collection `read` permission, he will be able to read all records.

**Comment by Natim** [comment] 2016-09-19 13:28
We want to keep the current behavior which is that you can read only records that you have permission on, when you create a record you can get the administrator right on this record.

**Comment by ptgamr** [comment] 2016-09-19 13:31
But how can user get to that record later again if he doesn't have `read` permission on the collection?

**Comment by Natim** [comment] 2016-09-19 13:33
Because he has got read permission on his records.

**Comment by Natim** [comment] 2016-09-19 13:33
You can try it it already works.

**Comment by ptgamr** [comment] 2016-09-19 13:36
I think you haven't got my point.

I'm trying to address what @leplatrem said ealier:

> Ok I think I get it. When a user has `record:create` we allow to read the collection metadata but not the list of records. I like it!

I think he should be able to list records, but only his own records.

**Comment by Natim** [comment] 2016-09-19 13:39
> I think he should be able to list records, but only his own records.

Yes I get it but it is already the case and already include in both @leplatrem proposition and implemented code. So there is nothing to change in the code or @leplatrem proposition to have what you are asking for.

**Comment by ptgamr** [comment] 2016-09-19 13:42
You mean it's already working like that? Ok, let me verify it again ... The last time I tried to list the collection, I'm able to get all records.

**Comment by leplatrem** [comment] 2016-09-19 13:54
So, let me try to sum it up: the idea is to make the necessary changes so that `record:create` would implicitly allow to read the collection object.

In terms of specs (and thus [unit tests to implement](http://blog.mathieu-leplatre.info/your-tests-as-your-specs.html)), it becomes:

If Alice has no permission to read the collection but has `record:create`
* she can read the collection object
* she obtains a 403 if she created no record in that collection (*current behaviour*)
* she can obtain the list of her own records (*current behaviour*)
* records of other users do not come up in the list  (*current behaviour*)
* she cannot read individual records of other users  (*current behaviour*)

If Alice has the permission to read the collection, she can read the collection object, and every records, but cannot create records (*current behaviour*).

**Comment by ptgamr** [comment] 2016-09-19 14:01
Thanks @leplatrem . I just verified again and it's working as expected now. Sorry I messed up a bit when receiving the 403 code when user haven't create any record. It make me think that I can't list the records if not granted `read` permission.

Could we change 403 to 404 code instead? As I think many applications base on 403 to actually handle Authorization error, sometime log the user out.

**Comment by Natim** [comment] 2016-09-19 14:06
The 403 is not to leak any information to not authorized users about the fact that the collection exists.

**Comment by ptgamr** [comment] 2016-09-19 14:09
I think it's ok for who got the `record:create` permission knows that the collection exists?

**Comment by leplatrem** [comment] 2016-09-19 14:18
> I think it's ok for who got the record:create permission knows that the collection exists?

Ok I think I see what you mean. Maybe we could change the current behaviour when the user has `record:create`: instead of returning a 403 when no record was created, we could return an empty list.

**Comment by ptgamr** [comment] 2016-09-19 14:19
That could be much better!

**Comment by leplatrem** [comment] 2016-09-28 08:49
Oh I realized this is a duplicate of #101 \o/ :)

**Closed** 2016-10-04 07:58 UTC
Labels: bug, duplicate, in progress, protocol
