### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by almet** [Kinto/kinto#208] opened 2015-10-06 14:36 UTC
I've spent some time doing a review of our actual documentation with @JeremiePat. Here are the outcomes of the discussion:

Index:
- The order of the section matters. It should be Overview, Concepts, Community and then Tutorials, Configuration and APIs;
- The menu on the left should be in the same order than these sections.

Overview:
- The FAQ should be separated from the overview page, and be linked from the the index;
- The comparison table should be in the FAQ page and not in the overview;

Tutorial:
- There is no installation tutorial.
- Requests and Responses should be separated.
- Is this tutorial really useful, since we want people to use our JavaScript client, should we drive them to do so, and let the httpie commands come for implementers who needs them?
- Should we include a Kinto.js tutorial here?

Installation:
- There should be some prerequesites in there "Check your environment".

Configuration:
- Default values could either be in a new column or on a new line;
- Broken links

APIs:
- Put the CheatCheet after the list of items;
- Remove the presence of HTTPie command line, it's not useful.
- The PATCH description should be made more explicit.
- Retrieving stored records: put the filtering / pagination *after* the API endpoint

Resource endpoints:
- It seems broken: no menu on le left.

Troubleshooting:
- Should mention the FAQ.

Contributing
- We should add links to the issues categories
- Add a link to the github repository
- Where are the docs ? How do I edit them ?
- the "hack" section is broken
- Troubleshooting should be updated: it's duplicated with the previous section

Misc:
- On RTD, the "stable" release actually displays the cliquet documentation
- On RTD, display the stable release and not "latest" by default

**Comment by Natim** [comment] 2015-10-06 14:55
> Is this tutorial really useful, since we want people to use our JavaScript client, should we drive them to do so, and let the httpie commands come for implementers who needs them?

I don't agree with that, this is the scope of kinto.js documentation.
I wish we had something like that: http://www.parse.com/docs on the ecosystem landing page.

**Comment by Natim** [comment] 2015-10-06 14:56
> Remove the presence of HTTPie command line, it's not useful.

I am not sure, this makes it reproducible and help remove blockers.

**Comment by ametaireau** [comment] 2015-10-06 21:02
I would actually find it very nice to have Kinto.js examples integrated with the current Kinto documentation, or at least have pointers there, Kinto.js being the reference JavaScript client.

I actually agree that the HTTPie commands are useful in order to reproduce a call (I've used them a few times already). But I think it is only useful for the persona who's implementing a Kinto client, and the core devs.

Publicizing the use of Kinto.js is IMO a good way to move the ecosystem forward, and while reviewing the docs, I was really asking myself why I wasn't seing some JS examples, or mentions of a JavaScript client earlier: I believe we should showcase the JavaScript client as the primary way to integrate with Kinto.

**Comment by phrawzty** [comment] 2015-10-09 07:55
> Remove the presence of HTTPie command line, it's not useful.

I have found the HTTPie examples to be highly useful, personally - my vote is to keep them.

**Comment by ametaireau** [comment] 2015-10-11 17:12
I would love to have @n1k0's feedback on this.

What do you think about having the Kinto.js client exposed directly in the Kinto server documentation? It could be just a link to the documentation of Kinto.js, the goal here would be to have the users use our solution with the smallest amount of indirection.

**Comment by n1k0** [comment] 2015-10-11 17:44
> What do you think about having the Kinto.js client exposed directly in the Kinto server documentation?

The thing is Kinto.js doesn't cover the whole Kinto API, and we should definitely keep the lower level HTTP req/rep examples.

Of course, linking to the client docs wherever applicable would be useful (eg. synchronization, backoff, etc.)

> It could be just a link to the documentation of Kinto.js, the goal here would be to have the users use our solution with the smallest amount of indirection.

**Comment by ametaireau** [comment] 2015-10-11 18:19
sorry if this was unclear. I think we all agree on the fact that we should keep the HTTP API. I'm proposing to add pointers to the JavaScript client, because it's not the case currently and seems to be missing.

**Comment by leplatrem** [comment] 2016-03-15 16:03
I propose that we close this *meta* issue and re-spawn scoped dedicated issues for the remaining items.

**Comment by almet** [comment] 2016-03-16 01:00
+1

**Comment by glasserc** [comment] 2016-04-28 20:56
>   * The order of the section matters. It should be Overview, Concepts, Community and then Tutorials, Configuration and APIs;
>   * The menu on the left should be in the same order than these sections.

I don't see any "community" section. Was this renamed to "Contributing"? Or should there be a new order?

>  * Remove the presence of HTTPie command line, it's not useful.

What does this mean? Remove the commands that demonstrate how to actually make the requests? I think those are useful, so maybe you're talking about something else.

>  Resource endpoints
>   * It seems broken: no menu on le left.

What does this mean? The fact that there's no menu for "Resource endpoints" subsection titles on the left side? I believe this is just due to the depth of the section ("Resource endpoints" is a sub-subsection) since none of its siblings have menus for their titles either.

>  * the "hack" section is broken

How is it broken?

The remaining tasks are either already done or I just created issues for them (see #562, #563, #564, #565, #566, #567, #568, #569, #570, and possibly others). Please feel free to create issues for the remaining four issues described above, or mention that they've been fixed or aren't valid, so we can close this one :)

**Comment by almet** [comment] 2016-05-02 10:58
> What does this mean? Remove the commands that demonstrate how to actually make the requests? I think those are useful, so maybe you're talking about something else.

That's what I meant, yes. See #502 for more info on this.

>I don't see any "community" section. Was this renamed to "Contributing"? Or should there be a new order?

There's a big "Community" section in the front page, but it's not reflected in the menu on the left: these two should be the same, and in the same order.

> Resource endpoints are broken

They're broken in the sense that if you actually navigate to a specific example, the according section should be highlighted on the left menu, but it's currently not the case. At least the "API" section should be highlighted.

> the "hack" section is broken

I cannot find anymore why it's broken, so let's consider it's ok!

**Comment by glasserc** [comment] 2016-05-02 19:36
OK. Since #502 is already open, and I've just created #580 and #581, I'd like to close this issue.

**Closed** 2016-05-03 12:12 UTC
Labels: documentation, in progress
